version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
  aws-cli: circleci/aws-cli@2.0.3
  coveralls: coveralls/coveralls@1.0.6

jobs:
  unit_test:
    docker:
      - image: cimg/node:14.15
      - run:
          name: Test
          command: npm test

  publish_on_version_change:
    docker:
      - image: cimg/node:14.15

    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys:
          fingerprints:
            - "49:dd:95:76:13:c0:cd:9d:75:48:b0:30:5c:3c:4c:17"

      - run:
          name: Release version
          command: ./.circleci/scripts/release_version.sh << pipeline.git.base_revision >>

workflows:
  version: 2
  test:
    jobs:
      - unit_test
      - publish_on_version_change:
          context: salto
          filters:
            branches:
              only:
                - main
          requires:
            - build
            - unit_test
